stages:
  train_model:
    cmd: python main.py
    deps:
    - data/california_housing.csv
    - src/train.py
    params:
    - model_params
    outs:
    - models/model.pkl
    metrics:
    - metrics.json:
        cache: false
