name: Train Model

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install dvc

    - name: DVC pull data and model
      run: dvc pull || echo "No remote configured, skipping"

    - name: Train model
      run: python main.py

    - name: Check model exists
      run: test -f models/model.pkl
